name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/cache@v1
      id: cache-lammps
      with:
        path: build/lammps-build
        key: ${{ runner.os }}-lammps-${{ hashFiles('**/deps/lammps/*') }}
        restore-keys: |
          ${{ runner.os }}-lammps-

    - name: Install Package Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libopenmpi-dev libboost-all-dev

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        # we need to install numpy first because of something phonopy does in its setup
        pip install -r <(grep numpy requirements.txt)
        pip install -r requirements.txt

    - name: Configure (CMAKE)
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug -DSP2_ENABLE_TESTS=ON ../

    - name: Build LAMMPS
      if: steps.cache-lammps.outputs.cache-hit != 'true'
      run: |
        cd build
        grep lammps Makefile
        make -j2 lammps_external

    - name: Make
      run: |
        cd build
        # We want `--keep-going` just in case there are multiple errors
        make -j2 --keep-going

    - name: Test
      run: build/src/sp2 --test
